--liquibase formatted sql
--changeset nilima:V20190408193729__al_tb_swd_scheme_eligibility_08042019.sql
CREATE TABLE tb_swd_scheme_eligibility(
  SDSCHE_ID BIGINT(12) NOT NULL,
  SDSCH_ID VARCHAR(45) NULL,
  SDSCHE_FACT_APL BIGINT(12) NULL,
  SDSCHE_CRITERIA BIGINT(12) NULL,
  SDSCHE_RENGFROM VARCHAR(50) NULL,
  SDSCHE_RENGTO VARCHAR(50) NULL,
  SDSCHE_GRID VARCHAR(10) NULL,
  SDSCHE_PAYSCH BIGINT(12) NULL,
  SDSCHE_AMT DECIMAL(15,2) NULL,
  ORGID BIGINT(12) NULL,
  CREATED_BY BIGINT(12) NULL,
  CREATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  UPDATED_DATE DATETIME NULL,
  LG_IP_MAC VARCHAR(100) NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  TB_SWD_SCHEME_ElIGIBILITYcol VARCHAR(45) NULL,
  PRIMARY KEY (SDSCHE_ID));
 
 --liquibase formatted sql
--changeset nilima:V20190408193729__al_tb_swd_scheme_eligibility_080420191.sql
  CREATE TABLE tb_swd_scheme_eligibility_hist(
  SDSCHE_HIST_ID BIGINT(12) NOT NULL,
  SDSCHE_ID BIGINT(12),
  SDSCH_ID VARCHAR(45) NULL,
  SDSCHE_FACT_APL BIGINT(12) NULL,
  SDSCHE_CRITERIA BIGINT(12) NULL,
  SDSCHE_RENGFROM VARCHAR(50) NULL,
  SDSCHE_RENGTO VARCHAR(50) NULL,
  SDSCHE_GRID VARCHAR(10) NULL,
  SDSCHE_PAYSCH BIGINT(12) NULL,
  SDSCHE_AMT DECIMAL(15,2) NULL,
  H_STAT CHAR(1),
  ORGID BIGINT(12) NULL,
  CREATED_BY BIGINT(12) NULL,
  CREATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  UPDATED_DATE DATETIME NULL,
  LG_IP_MAC VARCHAR(100) NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  TB_SWD_SCHEME_ElIGIBILITYcol VARCHAR(45) NULL,
  PRIMARY KEY (SDSCHE_ID));